import 'package:firebase_core/firebase_core.dart';

/// Hand-written Firebase options (normally generated by `flutterfire
/// configure`). Values mirror `android/app/google-services.json`
/// (gitignored) for project `firebrat-8c597`. Android-only: there is no
/// iOS target in this project.
class DefaultFirebaseOptions {
  static FirebaseOptions get android => const FirebaseOptions(
        apiKey: 'AIzaSyDITjca7MSZbuhgqkGXn4JegSIXekU_3rk',
        appId: '1:657440934081:android:ffa7b93d66d61efd1bac40',
        messagingSenderId: '657440934081',
        projectId: 'firebrat-8c597',
        storageBucket: 'firebrat-8c597.firebasestorage.app',
      );

  static FirebaseOptions get currentPlatform => android;
}
