#!/bin/bash
# Firebrat one-command runner: detects your machine, asks two questions,
# writes .env, and boots the right compose profile.
#
#   ./run.sh                       # interactive: GPU? provider? key?
#   ./run.sh --provider local --model qwen3-1.7b
#   ./run.sh --provider nanogpt    # needs MODEL_API_KEY env or prompt
#   ./run.sh --cpu                 # force CPU profile (no GPU)
#   ./run.sh --workers 2           # >1 parallel conversions (needs headroom)
#
# Prerequisites: docker + docker compose plugin. GPU mode additionally
# needs the NVIDIA container toolkit. Without docker, see README.md
# "bare metal" (conda envs) — this script tells you that instead of dying.
set -euo pipefail
cd "$(dirname "$0")"

PROVIDER="" MODEL="qwen3-4b" FORCE_CPU=0 WORKERS=""

while [ $# -gt 0 ]; do
  case "$1" in
    --provider) PROVIDER="$2"; shift 2;;
    --model) MODEL="$2"; shift 2;;
    --cpu) FORCE_CPU=1; shift;;
    --workers) WORKERS="$2"; shift 2;;
    -h|--help) sed -n '2,12p' "$0"; exit 0;;
    *) echo "unknown flag $1 (see --help)"; exit 1;;
  esac
done

fail() { echo "ERROR: $1" >&2; exit 1; }

# ── 1. docker present? ─────────────────────────────────────────────
if ! command -v docker >/dev/null 2>&1; then
  cat >&2 <<'EOF'
Docker isn't installed. Either install it (https://docs.docker.com/get-docker)
and re-run ./run.sh, or go bare metal: three conda envs per AGENTS.md, then
  cd backend && PYTHONPATH=backend <serve-python> -m uvicorn server.main:app --port 8000
EOF
  exit 1
fi
docker compose version >/dev/null 2>&1 || fail "docker compose plugin missing (need Docker 20.10+)."

# ── 2. GPU? how much VRAM? ─────────────────────────────────────────
GPU_NAME=""; VRAM_MB=0
if [ "$FORCE_CPU" -eq 0 ] && command -v nvidia-smi >/dev/null 2>&1; then
  GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -n 1 || true)
  VRAM_MB=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -n 1 | tr -d ' ' || echo 0)
fi
if docker info 2>/dev/null | grep -qi "nvidia.*runtime\|runtimes.*nvidia"; then
  HAS_NVIDIA_RUNTIME=1
else
  HAS_NVIDIA_RUNTIME=0
fi

# ── 3. provider (default: local when a usable GPU exists, else nanogpt) ──
if [ -z "$PROVIDER" ]; then
  if [ -n "$GPU_NAME" ] && [ "$HAS_NVIDIA_RUNTIME" -eq 1 ]; then
    echo "Detected GPU: $GPU_NAME (${VRAM_MB} MiB), nvidia runtime OK."
    read -r -p "LLM provider [local/nanogpt] (default local)? " PROVIDER
    PROVIDER=${PROVIDER:-local}
  else
    [ -n "$GPU_NAME" ] && echo "GPU present but no nvidia container runtime — local mode unavailable." \
      || echo "No GPU detected."
    PROVIDER=nanogpt
  fi
fi
if [ "$PROVIDER" != "local" ] && [ "$PROVIDER" != "nanogpt" ]; then
  fail "provider must be local or nanogpt"
fi

# ── 4. model preset sized to VRAM (local mode) ─────────────────────
if [ "$PROVIDER" = "local" ]; then
  if [ "$VRAM_MB" -gt 0 ] && [ "$VRAM_MB" -lt 10000 ] && [ "$MODEL" = "qwen3-4b" ]; then
    echo "Only ${VRAM_MB} MiB VRAM — qwen3-4b needs ~11GB. Falling back to qwen3-1.7b (~4GB)."
    MODEL="qwen3-1.7b"
  fi
  case "$MODEL" in
    qwen3-1.7b|qwen3-4b|qwen3-8b) ;;
    *) fail "model must be qwen3-1.7b, qwen3-4b, or qwen3-8b";;
  esac
fi

# ── 5. API key (nanogpt mode) ───────────────────────────────────────
if [ "$PROVIDER" = "nanogpt" ] && [ -z "${MODEL_API_KEY:-}" ]; then
  read -r -s -p "nano-gpt MODEL_API_KEY: " MODEL_API_KEY; echo
  [ -n "$MODEL_API_KEY" ] || fail "MODEL_API_KEY is required for nanogpt mode."
fi

# ── 6. write .env (compose reads it; never committed — see .gitignore) ──
{
  echo "# generated by ./run.sh on $(date -u +%FT%TZ) — safe to delete, re-run to regenerate"
  echo "MODEL_API_KEY=${MODEL_API_KEY:-}"
  echo "LLM_PROVIDER=$PROVIDER"
  echo "LOCAL_MODEL_PRESET=$MODEL"
  echo "LOCAL_MODEL_DIR=/models"
  [ -n "$WORKERS" ] && echo "FIREBRAT_MAX_CONCURRENT_JOBS=$WORKERS"
} > .env
echo "wrote .env (provider=$PROVIDER model=$MODEL)"

# ── 7. boot ─────────────────────────────────────────────────────────
if [ "$PROVIDER" = "local" ]; then
  [ "$FORCE_CPU" -eq 0 ] || fail "local provider needs a GPU; drop --cpu."
  [ "$HAS_NVIDIA_RUNTIME" -eq 1 ] || fail "nvidia container runtime not found — install nvidia-container-toolkit first."
  echo "Starting GPU profile (first boot downloads ~2-8GB weights, then serves the app)…"
  exec docker compose --profile gpu up --build -d
else
  if [ "$FORCE_CPU" -eq 1 ] || [ -z "$GPU_NAME" ]; then
    echo "Starting CPU profile…"
    exec docker compose --profile cpu up --build -d
  else
    echo "Starting GPU profile (extraction + TTS on GPU, LLM via nano-gpt)…"
    exec docker compose --profile gpu up --build -d
  fi
fi
